include:
  # ____NPM PLUS____
  - npm_plus/npm_plus.yaml
  - crowdsec/crowdsec.yaml
  - dragonfly_db/drag.db.yaml
  - arcane/arcane.yaml
  - caddy/caddy.yaml
  - geoipupdate/geoipupdate.yaml
  - redisinsight/redisinsight.yaml
  - astro/astro.yaml
  - socket-proxy/socket-proxy.yaml
  - authentik/authentik.yaml
  - rust_fs/rust.fs.yaml
  - redpanda/redpanda.yaml
  - pg/pg.yaml

networks:
  # internal services
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24 # same as current
  redpanda_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
  # npm + public facing
  proxy:
    driver: bridge

volumes:
  astro-static:
    external: true
