# # Arcane Docker Compose Configuration
# # Generated at 5/6/2026, 5:02:19 PM
services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    restart: unless-stopped

    depends_on:
      - socket-proxy
    volumes:
      - ./arcane-data:/data

    environment:
      - APP_URL=https://arcane.fast-web-tech.co.uk
      - DOCKER_HOST=tcp://socket-proxy:2375
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - OIDC_ENABLED=false
      - DATABASE_URL=file:/data/arcane.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate

    networks:
      - internal
