services:
  rustfs_perms:
    image: alpine:latest
    user: root
    volumes:
      - ./data:/fix_path
    command: sh -c "chown -R 10001:10001 /fix_path"
    networks:
      - internal

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    depends_on:
      rustfs_perms:
        condition: service_completed_successfully
    env_file:
      - ../.env
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "9080:9000"
      - "9081:9001"
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_OBS_LOGGER_LEVEL: "info"
    volumes:
      - ./data:/data
    command:
      - /data
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -fsS http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal
