services:
  rustfs_perms:
    image: alpine:latest
    user: root
    volumes:
      - ./data:/fix_path
    command: sh -c "chown -R 10001:10001 /fix_path"
    networks:
      - internal

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    depends_on:
      rustfs_perms:
        condition: service_completed_successfully
    env_file:
      - ../.env
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "9080:9000"
      - "9081:9001"
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      RUSTFS_CONSOLE_ENABLE: "true"
    volumes:
      - ./data:/data
    command:
      - --console-enable
      - --access-key
      - ${RUSTFS_ACCESS_KEY}
      - --secret-key
      - ${RUSTFS_SECRET_KEY}
      - /data
    networks:
      - internal
